[package]
name = "taphle-ios-entry"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
tapHLE = { path = "../../.." }

[patch."https://github.com/touchHLE/rust-sdl2"]
sdl2 = { path = "../../../vendor/rust-sdl2" }
sdl2-sys = { path = "../../../vendor/rust-sdl2/sdl2-sys" }
